### ISSUE TITLE
Replace uuid.New()/uuid.NewString() with a safe alternative

### ISSUE THREAD

**Issue by jay-dee7** [containerish/OpenRegistry#125]
**Describe the bug**
We're using a lot of uuids and they're generated using a non-safe method. Both `uuid.New()` and `uuid.NewString()` can panic and a better way could be to use `id, err := uuid.NewRandom()`

**To Reproduce**
nil, this bug hasn't occurred so far

**Expected behavior**
creating uuids should never result in panics and if they panic, the error should be handled.

**Screenshots**
<img width="1652" alt="Screenshot 2022-03-28 at 1 24 25 AM" src="https://user-images.githubusercontent.com/10788442/160298383-164768c6-56d9-493c-9931-ca710f67eb86.png">

**Log Files**
nil

**Desktop (please complete the following information):**
nil
**Additional context**
nil

**Comment by guacamole** [comment]
this issue is resolved by pr #143
