### ISSUE TITLE
Request for Feedback: OCI image-spec 1.1.0

### ISSUE THREAD

**Issue by sudo-bmitch** [containerish/OpenRegistry#357]
OCI is approaching a 1.1.0 release on the image-spec and distribution-spec, so we are reaching out to implementations to see if you have any concerns implementing support for those changes that we should address before a GA release.

A full diff of the changes can be viewed at:

- image-spec: https://github.com/opencontainers/image-spec/compare/v1.0.2...opencontainers:image-spec:main
- distribution-spec: https://github.com/opencontainers/distribution-spec/compare/v1.0.1...main

I'm happy to take feedback here, you can raise an issue in OCI, or respond in our tracking issue at https://github.com/opencontainers/image-spec/issues/1093.

**Comment by jay-dee7** [comment]
Hey @sudo-bmitch, Thanks a ton for letting us know in advance. We're all okay the coming changes & looking forward to add the support for all of them :)

**Comment by sudo-bmitch** [comment]
Thanks @jay-dee7! I'll close this so it's not cluttering your issues, but feel free to reach out here or over in OCI if you have further feedback.
