### ISSUE TITLE
Add catalog api for the registry

### ISSUE THREAD

**Issue by jay-dee7** [containerish/OpenRegistry#5]
Images are stored in collections, known as a repository, which is keyed by a `name`, as seen throughout the API specification. A registry instance may contain several repositories. The list of available repositories is made available through the _catalog_.

The catalog for a given registry can be retrieved with the following request:

```
GET /v2/_catalog
```

By adding a catalog endpoint, we can support OCI Compliant content distribution (only partial) and also use this endpoint in our registry frontend to list repositories.

More about this endpoint can be found here:
1. [Docker Documentation](https://docs.docker.com/registry/spec/api/#listing-repositories)
2. [OCI Specification Documentation](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery)

**Comment by guacamole** [comment]
This issue was resolved by PR #35
