### ISSUE TITLE
update which skynet package is used

### ISSUE THREAD

**Issue by vbatts** [containerish/OpenRegistry#79]
currently, https://github.com/containerish/OpenRegistry/blob/c7bc9ba85b92ad1c4b59f5b50caf2a1fe8bac967/skynet/skynet.go#L9 imports from https://github.com/NebulousLabs/go-skynet which appears to be archived an directs users to use https://github.com/SkynetLabs/go-skynet instead

**Comment by jay-dee7** [comment]
Hey @vbatts, we tried switching to the new skynet lib, but that actually breaks our builds. We're maintaining a fork of the Skynet Go library, which we'll use instead of this one.

Thanks a ton for opening this issue, it'll now be fixed sooner than we ought to haha
