### ISSUE TITLE
Extract the metadata method from OpenRegistry and put it in Skynet fork

### ISSUE THREAD

**Issue by guacamole** [containerish/OpenRegistry#85]
[code reference](https://github.com/containerish/OpenRegistry/pull/84/files?authenticity_token=b9BMrEAFtm7YZb6fJli0ceK84lF0PY423s6CtYEuLs9CJmhaGlO646pQ%2BqTB2g26FYN0cWMsJgpyCVqj5WRoCQ%3D%3D&file-filters%5B%5D=.example&file-filters%5B%5D=.go&file-filters%5B%5D=.mod#diff-5d607a5541c468b79854038ee0914b88951ae90bdb7228c00e637f0351c344ceL88)

**Comment by jay-dee7** [comment]
Now with https://github.com/containerish/go-skynet/pull/4 merged, we should be good to close this one after changing the reference to skynet sdk metadata in OpenRegistry
